import { HotelListDataType } from './HotelListDataType';

export const hotelListMockData: HotelListDataType = [
  {
    id: 0,
    name: '어텀 호텔',
    accommodationOption: {
      capacity: 0,
      pricePerNight: 150000,
      accommodationType: 'NORMAL',
      bedroomCount: 0,
      restroomCount: 0,
      restroomType: 'PRIVATE',
      hasKitchen: true,
      hasInternet: true,
      hasAirconditioner: true,
      hasHairdrier: true,
    },
    totalPrice: 0,
    reviewRating: 0,
    reviewCounts: 0,
    mainImage: 'string',
  },
  {
    id: 1,
    name: '롤로 호텔',
    accommodationOption: {
      capacity: 0,
      pricePerNight: 120000,
      accommodationType: 'NORMAL',
      bedroomCount: 0,
      restroomCount: 0,
      restroomType: 'PRIVATE',
      hasKitchen: true,
      hasInternet: true,
      hasAirconditioner: true,
      hasHairdrier: true,
    },
    totalPrice: 0,
    reviewRating: 0,
    reviewCounts: 0,
    mainImage: 'string',
  },
  {
    id: 2,
    name: '프레디 호텔',
    accommodationOption: {
      capacity: 0,
      pricePerNight: 140000,
      accommodationType: 'NORMAL',
      bedroomCount: 0,
      restroomCount: 0,
      restroomType: 'PRIVATE',
      hasKitchen: true,
      hasInternet: true,
      hasAirconditioner: true,
      hasHairdrier: true,
    },
    totalPrice: 0,
    reviewRating: 0,
    reviewCounts: 0,
    mainImage: 'string',
  },
];